### PR TITLE
Add foss build variant

### PR DESCRIPTION
**Pull request by Rudloff**
This PR adds a `foss` build variant that does not require any non-free libraries.
If the parent uses a variant named `foss`, the library will automatically also use this variant.

(It might be possible to refactor `AnalyticsApplication` in order to duplicate less code.)

### CODE REVIEW

**Comment by devgianlu** [comment]
Does this work? If so I'll refactor this and merge it.

**Comment by Rudloff** [comment]
Yes, DNS Hero 1.1.2 builds and works correctly with this.

**Comment by devgianlu** [comment]
Do I have to create another version?

**Comment by Rudloff** [comment]
Yes, we will need a new release of DNS Hero that includes a recent CommonUtils in submodules.

**Pull request merged**
